# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'medical_warehouse'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'medical_warehouse'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

# Configuring models
models:
  medical_warehouse:
    # Staging models - materialized as views (lightweight, always up-to-date)
    staging:
      +materialized: view
      +schema: staging
    
    # Marts models - materialized as tables (for performance)
    marts:
      +materialized: table
      +schema: marts